language: python
dist: xenial
python: 3.7
install:
  - cd confessions-rest && pip install -r requirements.txt
stages:
  - test
jobs:
  include:
    - stage: test
      script:
        - coverage run --source='.' manage.py test --settings=confessions_rest.settings_unittest
        - coverage xml
        - cd .. && sonar-scanner
env:
  - DJANGO_SETTINGS_MODULE: confessions_rest.settings_unittest
addons:
  sonarcloud:
    organization: "snemmani" # the key of the org you chose at step #3
deploy:
  provider: heroku
  app: confessions-asns
  on:
    branch: develop
    repo: snemmani/confessions
  api_key:
    secure: $HEROKU_TOKEN
