language: python
dist: trusty
python:
  - "3.7"
install:
  - cd confessions-rest && pip install -r requirements.txt
stages:
  - test
jobs:
  include:
    - stage: test
      script: cd confessions-rest && python manage.py test
env:
  - DJANGO_SETTINGS_MODULE: confessions_rest.settings_unittest


