language: python
dist: xenial
python: 3.7
install:
- cd confessions-rest && pip install -r requirements.txt
stages:
- test
jobs:
  include:
  - stage: test
    script:
    - coverage run --source='.' manage.py test --settings=confessions_rest.settings_unittest
    - coverage xml
    - cd .. && sonar-scanner
env:
- DJANGO_SETTINGS_MODULE: confessions_rest.settings_unittest
addons:
  sonarcloud:
    organization: snemmani
deploy:
  provider: heroku
  api_key:
    secure: KTncelDFXfeCggA1ivq5Bbr/mHhrFcpB4+rZfcmEAap+Ry3inNZHGbwyHAn5g+Js2Xo+w/9IU3kTjMtk26A/JuMeYHa4BxRWIVY9aPlq1rL4GwgSaPUfpNeOvk6NzmBnrdolj1eE2uQ+P02DNwCt6uWO5qdOl/usLHyj/a3DFwpG/0H6G58xTNR5NxzXLMinnkOGwDcz9fie5B/pJ/vnDQa40JSAjIC/G9F+MgSmRBHng6iMQK99t+Cfj4XSCXAauhaFdL1x/KlMX2gMsOPUz6hgkv3bKNgWCA59jAtxkKg2iCtga9CZg/zSJNt1Jo1WRMdQ/WnHDIA9NOgsr2NPlBEnfKEnFy83DqYvsbBMBpjoErtLQLyBx3imidU1D9r69p5cDoAckEsZsxlKvxF+EbjyLHej7S/7kZXvg/kyfYhU9/PLVnJ5VJzuVLSBSO5Q51IsgJhjVGIaHnLOYfT0YEuG/MP+aE1moa6L2OjpJLwb1AH+ybAEocoNJDTiNXfJOvrips4gU3A405rh8ws2s/bVkxglCYKXz4YmZJF89n+u8Q3gFyq8llm/Ybd3RS6shxH4fTYzSucR9b1Jkmg6s273FXnx1GR43Gf1Ut992x7Z/DjqSwdoHA7SP96duxkaOkK7T2HuoHG/J3+id0OJlFynXBu1fcxdy4mlsnDm+q0=
  app: confessions-asns
  on:
    repo: snemmani/confessions
    branch: develop
  skip_cleanup: 'true'
