language: python
dist: xenial
python: 3.7
install:
  - cd confessions-rest && pip install -r requirements.txt
stages:
  - test
jobs:
  include:
    - stage: test
      script:
        - python manage.py test
        - sonar-scanner
env:
  - DJANGO_SETTINGS_MODULE: confessions_rest.settings_unittest
addons:
  sonarcloud:
    organization: "snemmani" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN" # encrypted value of your token

