language: python
dist: xenial
python: 3.7
install:
- cd confessions-rest && pip install -r requirements.txt
stages:
- test
jobs:
  include:
  - stage: test
    script:
    - coverage run --source='.' manage.py test --settings=confessions_rest.settings_unittest
    - coverage xml
    - cd .. && sonar-scanner
env:
- DJANGO_SETTINGS_MODULE: confessions_rest.settings_unittest
addons:
  sonarcloud:
    organization: snemmani
deploy:
  provider: heroku
  api_key:
    secure: b0bmih1CGVvkeOXWkARfX1a+L8DA33ncnvjot/4kGMH7e8eKZc4m4ti42EUTFYFgmLTucx7nATGl+Vgoe6Kfumj2SZebuVuRo4UCWxVHdnixoWTgHMIRBHj/90GyMCxxTd7lK+CEktHuFDHRUqNfb42IQxT8pAjyFLzrIzNZp31uUMoOEacgYvhF3ocsPenT7tygM+8VFMHF8BAKIm3/0e00/vpO4/trY028evfjGgKyJi6I/R1zHX76k+ZztjnIuSRt+imwMg7bANUbiiiLfKxQrI1fi3XABRadt39qHkm4sOpGlhUk0N/YWlVANZfSdaJjAuo4F43W/fPhcCnIJcMyluc5cXsu7z4Xy0PSmhh9t1lchSPHX40IqHWj/9qDCKyd1jhmu6gPK1tXX9qOznnAu2xFFcyMnrSwoGQM6dhudeHHvRG+A8s0p7iXHNtBKNbpEwMtKfWxnW8/9xgtSn0QE/PSdqUFaqSZ05EqwBfZZTnxUTzo6ztaT1JvYsbRs4DwzmiZ8PgZW/iZxQlzRoN+C1fssYEsG0f2PwbTRvMZxRKKoDUAdvppyjILiXHBfO8+ow+H1dRYu/NFkNCc0OrSpQR/4KgAEIvMc2KlkyB7s3KKL2CkSGfmLx/E1BTr46clf1Nve3Uw97GknF/mQv1gWNe2yM+nzgPWA+5LrG4=
  app: confessions-asns
  on:
    repo: snemmani/confessions
    branch: develop
  skip_cleanup: 'true'
