# Generated by Django 2.2.7 on 2019-12-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20191120_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='downvote_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='upvote_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
