# Generated by Django 3.1 on 2020-08-07 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rest', '0002_upvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('vote_type', models.IntegerField(choices=[(1, 'UPVOTE'), (2, 'DOWNVOTE')], default=1)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='comment',
            name='downvote_count',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='upvote_count',
        ),
        migrations.DeleteModel(
            name='Upvote',
        ),
        migrations.AddField(
            model_name='vote',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upvotes', to='rest.comment'),
        ),
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
