# Generated by Django 3.1 on 2020-08-07 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rest', '0003_auto_20200807_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='confession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confession_votes', to='rest.confession'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comment_votes', to='rest.comment'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
